/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("factories").del();
  await knex("factories").insert([
    {
      id: knex.fn.uuid(),
      factory_name: "Farming",
      level: 1,
      level: 0,
      cost: 0,
      min_population: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Crops",
      level: 1,
      level: 0,
      cost: 0,
      min_population: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Islands",
      level: 1,
      level: 0,
      cost: 0,
      min_population: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Mine",
      level: 1,
      level: 0,
      cost: 0,
      min_population: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Bakery",
      level: 2,
      cost: 125,
      min_population: 55,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Feed Mill",
      level: 3,
      cost: 150,
      min_population: 60,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Dairy Factory",
      level: 4,
      cost: 175,
      min_population: 65,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Sugar Factory",
      level: 7,
      cost: 250,
      min_population: 75,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Textile Factory",
      level: 9,
      cost: 500,
      min_population: 105,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Tailor Shop",
      level: 12,
      cost: 800,
      min_population: 195,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Snack Factory",
      level: 14,
      cost: 1300,
      min_population: 300,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Fast Food Restaurant",
      level: 16,
      cost: 2100,
      min_population: 425,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Paper Factory",
      level: 18,
      cost: 2800,
      min_population: 570,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Ice Cream Factory",
      level: 20,
      cost: 3600,
      min_population: 735,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Pastry Factory",
      level: 24,
      cost: 5300,
      min_population: 1100,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Jam Factory",
      level: 27,
      cost: 7100,
      min_population: 1480,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Rubber Factory",
      level: 29,
      cost: 9000,
      min_population: 1670,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Food Processing Factory",
      level: 31,
      cost: 12000,
      min_population: 1980,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Plastics Factory",
      level: 34,
      cost: 15000,
      min_population: 2375,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Household Goods Factory",
      level: 37,
      cost: 18000,
      min_population: 3130,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Candy Factory",
      level: 39,
      cost: 20000,
      min_population: 3190,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Mexican Restaurant",
      level: 43,
      cost: 33000,
      min_population: 3950,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Stationery Factory",
      level: 46,
      cost: 40000,
      min_population: 4930,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Furniture Factory",
      level: 47,
      cost: 48000,
      min_population: 4760,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Shoe Factory",
      level: 50,
      cost: 60000,
      min_population: 5465,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Jewelry Store",
      level: 53,
      cost: 70000,
      min_population: 5860,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Asian Restaurant",
      level: 56,
      cost: 95000,
      min_population: 7500,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Grill Factory",
      level: 59,
      cost: 115000,
      min_population: 8700,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Perfume Factory",
      level: 61,
      cost: 130000,
      min_population: 9480,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Beverage Factory",
      level: 65,
      cost: 190000,
      min_population: 10900,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Cake Factory",
      level: 66,
      cost: 200000,
      min_population: 11000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Hot Dog Factory",
      level: 68,
      cost: 220000,
      min_population: 11300,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "French Restaurant",
      level: 69,
      cost: 240000,
      min_population: 12180,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Coffee Factory",
      level: 72,
      cost: 270000,
      min_population: 12600,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Down Feather Factory",
      level: 74,
      cost: 290000,
      min_population: 13100,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Doll Factory",
      level: 76,
      cost: 310000,
      min_population: 13900,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Kitchenware Factory",
      level: 78,
      cost: 340000,
      min_population: 14500,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Music Factory",
      level: 82,
      cost: 390000,
      min_population: 15700,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Tea Factory",
      level: 84,
      cost: 405000,
      min_population: 16400,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Bouquet Factory",
      level: 87,
      cost: 420000,
      min_population: 17200,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Italian Restaurant",
      level: 92,
      cost: 450000,
      min_population: 17845,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Festivities Factory",
      level: 95,
      cost: 470000,
      min_population: 18500,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Gardening Supplies Factory",
      level: 97,
      cost: 500000,
      min_population: 20500,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Pet Supply Factory",
      level: 100,
      cost: 535000,
      min_population: 23500,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Vegan Cafe",
      level: 103,
      cost: 580000,
      min_population: 26000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Bag Factory",
      level: 107,
      cost: 630000,
      min_population: 28000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Train 1",
      level: 5,
      cost: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Train 2",
      level: 14,
      cost: 1000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Train 3",
      level: 25,
      cost: 14000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Frutus Isle",
      level: 29,
      cost: 0,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Olivia Isle",
      level: 35,
      cost: 11000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Tropica Isle",
      level: 41,
      cost: 15000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Fishermen's Isle",
      level: 52,
      cost: 45000,
    },
    {
      id: knex.fn.uuid(),
      factory_name: "Bonita Isle",
      level: 67,
      cost: 130000,
    },
  ]);
};
